# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Cache gradle files
      id: gradle-cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Compile with Gradle
      run: |
        ./gradlew compileJava
        ./gradlew compileTestJava

  Test:
    runs-on: ubuntu-latest
    needs: Compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Cache gradle files
      id: gradle-cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Test with Gradle
      run: ./gradlew test
    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: testReport
        path: build/reports

  Assemble:
    runs-on: ubuntu-latest
    needs: [Compile, Test]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Cache gradle files
      id: gradle-cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Assemble with Gradle
      run: ./gradlew assemble
    - name: Upload assembled jar file
      uses: actions/upload-artifact@v2
      with:
        name: buildJar
        path: build/libs

  Release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [Compile, Test, Assemble]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: buildJar
        path: release
    - id: outputReleaseName
      name: Display structure of downloaded files
      run: echo "jar_name=`ls`" >> $GITHUB_ENV
      working-directory: release
    - name: Release
      uses: softprops/action-gh-release@v0.1.5
      with:
        files: release/${{ env.jar_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
